apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "forebyggingsplan"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  tokenx:
    enabled: true
  image: {{image}}
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  accessPolicy:
    inbound:
      rules:
        - application: forebyggingsplan-frontend
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  env:
    - name: SERVER_PORT
      value: "8080"
