apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "forebyggingsplan"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{dbTier}}
        databases:
          - name: forebyggingsplan
            envVarPrefix: DB
  tokenx:
    enabled: true
  image: {{image}}
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    inbound:
      rules:
        - application: forebyggingsplan-frontend
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
  env:
    - name: SERVER_PORT
      value: "8080"
    - name: ALTINN_RETTIGHETER_PROXY_CLIENT_ID
      value: {{altinnRettigheterProxyClientId}}
    - name: ALTINN_RETTIGHETER_PROXY_URL
      value: "http://altinn-rettigheter-proxy.arbeidsgiver/altinn-rettigheter-proxy"
    - name: ALTINN_RETTIGHET_SERVICE_EDITION
      value: "{{altinnRettighetServiceEdition}}"
    - name: SANITY_HOST
      value: "https://2u7e6oll.api.sanity.io"
