apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: forebyggingsplan
  namespace: teamia
  labels:
    team: teamia
spec:
  receivers:
    slack:
      channel: {{slack-kanal}}
      # <!here> results in a @here message in Slack
      prependText: "<!here> | "
  alerts:
    - alert: Forebyggingsplan; applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="forebyggingsplan"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod -l app={{ $labels.app }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.app }} -n {{ $labels.namespace }}` for logger"
    - alert: Forebyggingsplan; høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="forebyggingsplan",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="forebyggingsplan"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
    - alert: Forebyggingsplan; feil i selftest # This alert uses a custom metric provided by https://github.com/navikt/common-java-modules
      expr: selftests_aggregate_result_status{app="forebyggingsplan"} > 0
      for: 1m
      action: "Sjekk app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt"
    - alert: Forebyggingsplan; Høy andel HTTP serverfeil (5xx responser)
      severity: danger
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"^5\\d\\d", namespace="teamia", app="forebyggingsplan"}[3m])) / sum by (backend) (rate(response_total{namespace="teamia", app="forebyggingsplan"}[3m])))) > 1
      for: 3m
      action: "Sjekk loggene for å se hvorfor forebyggingsplanen returnerer HTTP feilresponser"
    - alert: Forebyggingsplan; Høy andel HTTP klientfeil (4xx responser)
      severity: warning
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"^4\\d\\d", namespace="teamia", app="forebyggingsplan"}[3m])) / sum by (backend) (rate(response_total{namespace="teamia", app="forebyggingsplan"}[3m])))) > 10
      for: 3m
      action: "Sjekk loggene for å se hvorfor forebyggingsplanen returnerer HTTP feilresponser"
