name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
      - flytte-frontend-til-teamia-namespace--konfig-i-backend
    paths:
      - '.nais/alerts/alerts.yaml'
      - '.github/workflows/alerts-deploy.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts/alerts.yaml
          VARS: .nais/alerts/dev.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts/alerts.yaml
          VARS: .nais/alerts/prod.yaml

