name: "Build and deploy forebyggingsplan"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "navikt/pia-actions/forebyggingsplan-e2e@v1.0.1"
        name: "e2e-tester for forebyggingsplan"
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/cache@v3"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v3"
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Compile, run tests and build"
        run: "./gradlew build --no-daemon"
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v2"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push the Docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}

  "deployTilDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/deploy.yaml"
  "deployTilProd":
    name: "Deploy app to prod"
    needs: "deployTilDev"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/deploy.yaml"
