name: Build and deploy forebyggingsplan
run-name: Build and deploy || ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - main
      - update-dependencies-apr-2024

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    name: Build, test and push docker image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile, run tests and build
        run: ./gradlew build --no-daemon
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          tag: latest
          team: teamia
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          salsa: true
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-to-prod:
    name: Deploy to prod-gcp
    needs: docker-build-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/deploy.yaml
          VARS: .nais/prod.yaml

  deploy-to-dev:
    name: Deploy to dev-gcp
    needs: docker-build-push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/deploy.yaml
          VARS: .nais/dev.yaml

  trivy-scan:
    name: Scanner docker image med Trivy
    if: github.ref == 'refs/heads/main'
    needs: docker-build-push
    permissions:
      contents: read # to write sarif
      security-events: write # push sarif to GitHub security
      id-token: write # for nais/login
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/pia-actions/trivy-scan@v1 # https://github.com/navikt/pia-actions/tree/main/trivy-scan
        with:
          image: ${{ needs.docker-build-push.outputs.image }}
          team: teamia
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
