name: Build and deploy forebyggingsplan
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      contents: read # TODO: hvorfor er denne write i pia-sykefravarsstatistikk og lydia-api?
      id-token: write
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle # TODO: hvorfor mangler denne i lydia-api og pia-sykefravarsstatistikk?

      - uses: gradle/wrapper-validation-action@v1  # TODO: hvorfor mangler denne i lydia-api og pia-sykefravarsstatistikk?

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Compile, run tests and build
        run: ./gradlew build --no-daemon # TODO: Hvorfor --no-daemon? mangler i pia-sykefravarsstatistikk og lydia-api.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamia
          tag: latest #todo: bruk? ${{ github.ref == 'refs/heads/main' && 'latest' || 'branch_latest' }}
          platforms: linux/amd64,linux/arm64
          salsa: true
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
#    permissions: # Todo: hvorfor har ikke vi denne?
#      id-token: write
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]
    name: Deploy app to ${{ matrix.cluster }}
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Deploy application to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/deploy.yaml #Todo: rename til nais.yaml ?
          VARS: .nais/${{ matrix.cluster }}.yaml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

  deploy-branch-to-dev:
#    permissions: # Todo: hvorfor har ikke vi denne?
#      id-token: write
    name: Deploy branch to dev
    needs: build
    if: github.ref == 'refs/heads/utled-aggregert-statistikk'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Deploy app to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/deploy.yaml #Todo: rename til nais.yaml ?
          VARS: .nais/dev.yaml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

  trivy-scan:
    name: Scanner docker image med Trivy
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: read # to write sarif
      security-events: write # push sarif to GitHub security
      id-token: write # for nais/login
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/pia-actions/trivy-scan@v1 # https://github.com/navikt/pia-actions/tree/main/trivy-scan
        with:
          image: ${{ needs.build.outputs.image }}
          team: teamia
